### ISSUE TITLE
Cuda image `THIS IMAGE IS DEPRECATED and is scheduled for DELETION`

### ISSUE THREAD

**Issue by flexchar** [modal-labs/llammer#6]
Loading the example image provided in [`llm_vicuna.py`](https://github.com/modal-labs/quillman/blob/main/src/llm_vicuna.py) throws a huge warning:

```
==========
== CUDA ==
==========

CUDA Version 11.7.0

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md
```

I've tried updating it to later version and I found myself in the unfortunate rabbit hole of "pytorch has been compiled with the Cuda 11.7 version". 

I raise this issue hoping someone at their discretion could update providing an example of how it should be done. Thank you. :)

**Comment by sugiantolauw** [comment]
Change it to cuda:11.7.1 and it works a treat. 

Bear in mind, its still quite clunky, for me anyway. Especially the latency.

**Comment by flexchar** [comment]
@sugiantolauw can you please elaborate on the clunky and latency part?

**Comment by sugiantolauw** [comment]
1) From the time i speak to being transcribed into text, sometimes it took 20 seconds or more. And sometimes its not being transcribed. Just need to test this more by speaking directly to the mic or use airpod to do that.
2) What i asked to the bot sometimes its not being transcribed well. Again, this could probably the closeness to the mic issue. But i have tested this by speaking closely to the mic and still didnt transcribe it well. Need to test with airpod again to see if it helps.
3) When i asked for a book recommendations, sometimes i need to speak to it twice or more before it transcribed my voice. 
4) Output: Sometimes, the bot only voice only parts of the output and stopped but its still generating the text.

**Comment by flexchar** [comment]
Very interesting, thank you taking your time to share that, Sugianto. 

Were you able to notice a significant improvement using older NVIDIA image?

I've recently update my containers to use the newer to avoid the warning. I haven't noticed big changes but they all behave randomly time from time. I'm using for text generation with LLMs.

**Comment by luiscape** [comment]
Updating the base image should be fine, and it should get rid of the message.
