### ISSUE TITLE
modal : The term 'modal' is not recognized as the name of a cmdlet, function, script file, or operable program. 

### ISSUE THREAD

**Issue by rohansingh20** [modal-labs/llammer#7]
downloaded zip, ran `pip install modal-client`, then `modal serve src.app`, and got the following error:

`modal : The term 'modal' is not recognized as the name of a cmdlet, function, script file, or operable program. `
`Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
`At line:1 char:1`
`+ modal serve src.app`
`+ ~~~~~`
 `   + CategoryInfo          : ObjectNotFound: (modal:String) [], CommandNotFoundException`
  `  + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by jesulo** [comment]
Hi, do you have solve this?

**Comment by kning** [comment]
my guess here from the error message is modal wasn't installed correctly, do you have the logs for `pip install modal-client`? are you running it in a virtual environment?

**Comment by olle556** [comment]
use python3 -m modal command instead of just modal

**Comment by ekzhang** [comment]
Closing due to staleness — if you have issues finding the `modal` command, please create a separate issue. We've changed the name of the Modal package since Jul 2023
